export const packagesData = [
  {
    id: 1,
    title: 'Mediterranean Escape',
    location: 'Santorini, Greece',
    duration: '7 Days / 6 Nights',
    price: '$1,450',
    priceValue: 1450,
    originalPrice: 1690,
    discount: '-14% today',
    badge: 'Top pick',
    reviews: 214,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=-5',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500375592092-8c05f6f3d3b1?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Sunset cruise', 'Cliffside stay', 'Vineyard tour'],
    description: 'Unwind in whitewashed villages, sail to hidden coves, and savor Cycladic cuisine with a sea view.',
    inclusions: ['Round-trip flights', '4-star hotel stay with breakfast', 'Sunset catamaran cruise', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Travel insurance', 'Personal expenses'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Santorini', detail: 'Private transfer, hotel check-in, blue-dome village walk.' },
      { day: 'Day 2', title: 'Caldera cruise', detail: 'Catamaran with swim stops, sunset dinner on board.' },
      { day: 'Day 3', title: 'Wine & cuisine', detail: 'Vineyard tastings and a cliffside taverna evening.' },
      { day: 'Day 4-7', title: 'Beach and explore', detail: 'Red Beach, Oia photo walk, optional volcano hike, departure.' },
    ],
  },
  {
    id: 2,
    title: 'Safari & City Lights',
    location: 'Cape Town, South Africa',
    duration: '6 Days / 5 Nights',
    price: '$1,280',
    priceValue: 1280,
    originalPrice: 1490,
    discount: '-14% today',
    badge: 'Editor’s pick',
    reviews: 189,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Table Mountain', 'Winelands day trip', 'Safari drive'],
    description: 'Blend vibrant city life with a day in the wild. Taste world-class wines, then chase sunsets on the coast.',
    inclusions: ['Round-trip flights', 'Boutique hotel stay', 'Peninsula tour', 'Big Five safari drive'],
    notIncluded: ['Lunch and dinner', 'Optional shark cage diving', 'Visa fees (if applicable)'],
    itinerary: [
      { day: 'Day 1', title: 'Cape Town arrival', detail: 'Transfer to hotel, V&A Waterfront sunset stroll.' },
      { day: 'Day 2', title: 'Table Mountain', detail: 'Cableway up, city bowl viewpoints, Bo-Kaap walk.' },
      { day: 'Day 3', title: 'Cape Peninsula', detail: 'Chapman’s Peak, Cape Point, penguins at Boulders.' },
      { day: 'Day 4-6', title: 'Winelands & safari', detail: 'Franschhoek tastings, full-day safari drive, departure.' },
    ],
  },
  {
    id: 3,
    title: 'Island Hopper',
    location: 'Bali, Indonesia',
    duration: '5 Days / 4 Nights',
    price: '$980',
    priceValue: 980,
    originalPrice: 1120,
    discount: '-12% today',
    badge: 'Best value',
    reviews: 301,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Private villa', 'Nusa Penida tour', 'Spa day'],
    description: 'Stay in a private villa, explore turquoise bays, and recharge with a Balinese spa ritual.',
    inclusions: ['Round-trip flights', 'Private pool villa', 'Island hopping tour', 'Daily breakfast'],
    notIncluded: ['Lunch and dinner', 'Surf lessons', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Bali', detail: 'Private transfer to villa, poolside welcome dinner.' },
      { day: 'Day 2', title: 'Ubud & rice terraces', detail: 'Tegallalang, waterfalls, evening spa.' },
      { day: 'Day 3', title: 'Nusa Penida', detail: 'Day trip to Kelingking, Crystal Bay snorkeling.' },
      { day: 'Day 4-5', title: 'Beach and culture', detail: 'Temple visit, Seminyak beach time, departure.' },
    ],
  },
  {
    id: 4,
    title: 'Nordic Adventure',
    location: 'Reykjavik, Iceland',
    duration: '5 Days / 4 Nights',
    price: '$1,620',
    priceValue: 1620,
    originalPrice: 1790,
    discount: '-10% today',
    badge: 'Small groups',
    reviews: 142,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=-10',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=10',
    ],
    highlights: ['Blue Lagoon', 'Northern lights', 'Glacier hike'],
    description: 'Chase auroras, soak in geothermal spas, and walk ice fields with seasoned guides.',
    inclusions: ['Round-trip flights', 'City hotel with breakfast', 'Blue Lagoon entry', 'Glacier hiking tour'],
    notIncluded: ['Meals not listed', 'Winter gear rental', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Reykjavik', detail: 'Check-in, harbor walk, optional whale watching.' },
      { day: 'Day 2', title: 'Golden Circle', detail: 'Þingvellir, Geysir, Gullfoss with small-group guide.' },
      { day: 'Day 3', title: 'Glacier adventure', detail: 'South Coast and glacier hike with crampons.' },
      { day: 'Day 4-5', title: 'Blue Lagoon & lights', detail: 'Lagoon soak, northern lights hunt, departure.' },
    ],
  },
  {
    id: 5,
    title: 'Alpine Serenity',
    location: 'Zermatt, Switzerland',
    duration: '6 Days / 5 Nights',
    price: '$1,540',
    priceValue: 1540,
    originalPrice: 1740,
    discount: '-11% today',
    badge: 'Scenic rail',
    reviews: 97,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=-10',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=-10',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Matterhorn views', 'Glacier express', 'Mountain spa'],
    description: 'Slow down in car-free Zermatt, ride the Glacier Express, and unwind with alpine spa rituals.',
    inclusions: ['Round-trip flights', 'Mountain lodge stay', 'Glacier Express tickets', 'Spa access'],
    notIncluded: ['Lunch and dinner', 'Ski passes', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Zermatt arrival', detail: 'Train into the Alps, check-in, village stroll.' },
      { day: 'Day 2', title: 'Gornergrat views', detail: 'Cogwheel ride, Matterhorn panorama, alpine lunch.' },
      { day: 'Day 3', title: 'Glacier Express', detail: 'Scenic rail day with glass-dome coaches.' },
      { day: 'Day 4-6', title: 'Spa and trails', detail: 'Light hikes, spa day, cheese tasting, departure.' },
    ],
  },
  {
    id: 6,
    title: 'Desert & Skyscrapers',
    location: 'Dubai, UAE',
    duration: '4 Days / 3 Nights',
    price: '$890',
    priceValue: 890,
    originalPrice: 990,
    discount: '-10% today',
    badge: 'City + desert',
    reviews: 255,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop&sat=5',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=15',
    ],
    highlights: ['Desert safari', 'Skyline dinner', 'Souk walk'],
    description: 'Zip through golden dunes, dine above the clouds, and wander historic souks under neon skylines.',
    inclusions: ['Round-trip flights', 'City hotel stay', 'Desert safari with dinner', 'Airport transfers'],
    notIncluded: ['Lunch', 'Burj Khalifa tickets', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Dubai arrival', detail: 'Check-in, Dubai Mall fountains, Burj Khalifa at night.' },
      { day: 'Day 2', title: 'Old Dubai', detail: 'Creek abra ride, gold and spice souks, museum stop.' },
      { day: 'Day 3', title: 'Desert safari', detail: 'Dune bashing, sunset camp, belly dance dinner.' },
      { day: 'Day 4', title: 'Skyline brunch', detail: 'Sky-high brunch, beach time, departure.' },
    ],
  },
  {
    id: 7,
    title: 'Rainforest Retreat',
    location: 'Costa Rica',
    duration: '7 Days / 6 Nights',
    price: '$1,220',
    priceValue: 1220,
    originalPrice: 1340,
    discount: '-9% today',
    badge: 'Eco pick',
    reviews: 178,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop&sat=10',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Canopy zipline', 'Arenal hot springs', 'Wildlife tour'],
    description: 'Wake to toucans, zip through cloud forests, and soak in thermal springs at the foot of volcanoes.',
    inclusions: ['Round-trip flights', 'Eco-lodge stay', 'Guided rainforest tour', 'Hot springs evening'],
    notIncluded: ['Lunch and dinner', 'Adventure add-ons', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'San Jose arrival', detail: 'Transfer to eco-lodge, welcome dinner.' },
      { day: 'Day 2', title: 'Rainforest wildlife', detail: 'Guided morning walk, sloth and bird spotting.' },
      { day: 'Day 3', title: 'Zipline & hot springs', detail: 'Canopy zipline, evening soak at Arenal.' },
      { day: 'Day 4-7', title: 'Waterfalls & coffee', detail: 'La Fortuna waterfall, coffee farm visit, departure.' },
    ],
  },
  {
    id: 8,
    title: 'Heritage Trail',
    location: 'Kyoto, Japan',
    duration: '5 Days / 4 Nights',
    price: '$1,150',
    priceValue: 1150,
    originalPrice: 1280,
    discount: '-10% today',
    badge: 'Cultural',
    reviews: 233,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80&auto=format&fit=crop&sat=-5',
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=80&auto=format&fit=crop&sat=-5',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=-10',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Temple strolls', 'Tea ceremony', 'Arashiyama bamboo'],
    description: 'Walk lantern-lit lanes, sip ceremonial matcha, and drift through bamboo groves at sunrise.',
    inclusions: ['Round-trip flights', 'Ryokan stay with breakfast', 'Tea ceremony session', 'Local transit card'],
    notIncluded: ['Lunch and dinner', 'Kimono rental', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Kyoto arrival', detail: 'Check-in to ryokan, evening Gion walk.' },
      { day: 'Day 2', title: 'Temples & tea', detail: 'Kiyomizu-dera, tea ceremony, Nishiki Market bites.' },
      { day: 'Day 3', title: 'Arashiyama dawn', detail: 'Bamboo grove sunrise, river lunch, monkey park.' },
      { day: 'Day 4-5', title: 'Gardens & departure', detail: 'Zen gardens, souvenir time, flight home.' },
    ],
  },
  {
    id: 9,
    title: 'Coastal Charm',
    location: 'Lisbon, Portugal',
    duration: '5 Days / 4 Nights',
    price: '$920',
    priceValue: 920,
    originalPrice: 1020,
    discount: '-10% today',
    badge: 'Sunny escape',
    reviews: 164,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=20',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=15',
      'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Tram 28 ride', 'Fado night', 'Sintra palaces'],
    description: 'Ride yellow trams, taste pastéis de nata, and explore fairy-tale castles above the sea.',
    inclusions: ['Round-trip flights', 'Boutique stay with breakfast', 'Sintra day trip', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Optional surf lesson', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & Alfama', detail: 'Check-in, evening Fado and tapas.' },
      { day: 'Day 2', title: 'Lisbon icons', detail: 'Belém tower, Jerónimos, LX Factory sunset.' },
      { day: 'Day 3', title: 'Sintra palaces', detail: 'Pena Palace, Quinta da Regaleira, coastal Cabo da Roca.' },
      { day: 'Day 4-5', title: 'Markets & departure', detail: 'Time Out Market, riverfront bike, fly home.' },
    ],
  },
  {
    id: 10,
    title: 'Alpine Loop',
    location: 'Innsbruck, Austria',
    duration: '6 Days / 5 Nights',
    price: '$1,180',
    priceValue: 1180,
    originalPrice: 1320,
    discount: '-11% today',
    badge: 'Mountains',
    reviews: 121,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80&auto=format&fit=crop&sat=12',
    images: [
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Nordkette cable car', 'Swarovski Crystal Worlds', 'Alpine hike'],
    description: 'Glass mountains, pastel old towns, and crisp alpine air in Tyrol.',
    inclusions: ['Round-trip flights', 'Mountain-view hotel with breakfast', 'Cable car passes', 'Rail transfers'],
    notIncluded: ['Lunch and dinner', 'Ski passes', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & old town', detail: 'Check-in, Golden Roof stroll.' },
      { day: 'Day 2', title: 'Nordkette views', detail: 'Cable car to Hafelekar, café stop.' },
      { day: 'Day 3', title: 'Swarovski & Hall', detail: 'Crystal Worlds, medieval Hall in Tyrol.' },
      { day: 'Day 4-6', title: 'Alpine trails', detail: 'Light hike, spa time, departure.' },
    ],
  },
  {
    id: 11,
    title: 'City & Safari',
    location: 'Nairobi, Kenya',
    duration: '5 Days / 4 Nights',
    price: '$1,050',
    priceValue: 1050,
    originalPrice: 1180,
    discount: '-11% today',
    badge: 'Wildlife',
    reviews: 143,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=25',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=20',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Nairobi National Park', 'Giraffe Centre', 'Masai market'],
    description: 'Spot wildlife against a city skyline and dive into vibrant Kenyan culture.',
    inclusions: ['Round-trip flights', 'Hotel with breakfast', 'Half-day safari', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Visa fees', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & markets', detail: 'Check-in, Maasai market browsing.' },
      { day: 'Day 2', title: 'City safari', detail: 'Morning game drive, Giraffe Centre visit.' },
      { day: 'Day 3', title: 'Culture day', detail: 'National Museum, Karen Blixen, coffee tasting.' },
      { day: 'Day 4-5', title: 'Free & depart', detail: 'Optional day trip, flight home.' },
    ],
  },
  {
    id: 12,
    title: 'Andes Adventure',
    location: 'Cusco & Machu Picchu, Peru',
    duration: '6 Days / 5 Nights',
    price: '$1,480',
    priceValue: 1480,
    originalPrice: 1650,
    discount: '-10% today',
    badge: 'Bucket list',
    reviews: 276,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop&sat=20',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=20',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Sacred Valley', 'Machu Picchu entry', 'Cusco walking tour'],
    description: 'High-Andes history, quinoa feasts, and sunrise over Machu Picchu.',
    inclusions: ['Round-trip flights', 'Hotels with breakfast', 'Machu Picchu ticket & guide', 'Train + bus transfers'],
    notIncluded: ['Lunch and dinner', 'Huayna Picchu permit', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Cusco', detail: 'Acclimatize, coca tea, plaza walk.' },
      { day: 'Day 2', title: 'Sacred Valley', detail: 'Pisac, Ollantaytambo, Andean lunch.' },
      { day: 'Day 3', title: 'Machu Picchu', detail: 'Train, guided citadel tour, return to Cusco.' },
      { day: 'Day 4-6', title: 'Cusco & depart', detail: 'San Blas, café time, flight home.' },
    ],
  },
  {
    id: 13,
    title: 'Island Dreams',
    location: 'Phuket, Thailand',
    duration: '5 Days / 4 Nights',
    price: '$860',
    priceValue: 860,
    originalPrice: 950,
    discount: '-9% today',
    badge: 'Beach break',
    reviews: 312,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop&sat=15',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80&auto=format&fit=crop&sat=15',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=15',
    ],
    highlights: ['Phi Phi cruise', 'Thai cooking class', 'Old Town walk'],
    description: 'Emerald bays, island hopping, and food you will dream about for months.',
    inclusions: ['Round-trip flights', 'Resort stay with breakfast', 'Phi Phi day trip', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Diving excursions', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & beach', detail: 'Check-in, sunset at Karon.' },
      { day: 'Day 2', title: 'Phi Phi cruise', detail: 'Maya Bay photo stops, snorkel time.' },
      { day: 'Day 3', title: 'Culture & food', detail: 'Old Town stroll, cooking class.' },
      { day: 'Day 4-5', title: 'Free & depart', detail: 'Massage day, island café, fly home.' },
    ],
  },
  {
    id: 14,
    title: 'Cultural Capital',
    location: 'Rome, Italy',
    duration: '5 Days / 4 Nights',
    price: '$1,050',
    priceValue: 1050,
    originalPrice: 1180,
    discount: '-11% today',
    badge: 'History',
    reviews: 402,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=5',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Colosseum fast track', 'Vatican tour', 'Trastevere food walk'],
    description: 'Ancient stones, espresso bars, and late-night gelato runs.',
    inclusions: ['Round-trip flights', 'Central hotel with breakfast', 'Skip-the-line Vatican & Colosseum', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'City tax', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & piazzas', detail: 'Trevi, Pantheon, aperitivo.' },
      { day: 'Day 2', title: 'Colosseum & Forum', detail: 'Guided ancient Rome morning.' },
      { day: 'Day 3', title: 'Vatican museums', detail: 'Sistine Chapel, St. Peter’s views.' },
      { day: 'Day 4-5', title: 'Hidden Rome', detail: 'Trastevere tastes, final shopping, depart.' },
    ],
  },
  {
    id: 15,
    title: 'Desert Glow',
    location: 'Marrakech, Morocco',
    duration: '5 Days / 4 Nights',
    price: '$970',
    priceValue: 970,
    originalPrice: 1090,
    discount: '-11% today',
    badge: 'Riads',
    reviews: 178,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop&sat=18',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=18',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=10',
    ],
    highlights: ['Medina souks', 'Atlas day trip', 'Desert dinner'],
    description: 'Labyrinthine alleys, rooftop sunsets, and spices that linger.',
    inclusions: ['Round-trip flights', 'Riad stay with breakfast', 'Atlas Mountains excursion', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Hammam session', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & souks', detail: 'Jemaa el-Fnaa evening lights.' },
      { day: 'Day 2', title: 'Palaces & gardens', detail: 'Bahia Palace, Majorelle garden.' },
      { day: 'Day 3', title: 'Atlas adventure', detail: 'Imlil village, Berber lunch.' },
      { day: 'Day 4-5', title: 'Desert dinner', detail: 'Agafay sunset camp, depart.' },
    ],
  },
  {
    id: 16,
    title: 'Nordic Lights',
    location: 'Tromsø, Norway',
    duration: '5 Days / 4 Nights',
    price: '$1,450',
    priceValue: 1450,
    originalPrice: 1610,
    discount: '-10% today',
    badge: 'Aurora',
    reviews: 133,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80&auto=format&fit=crop&sat=0',
    images: [
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=0',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=-5',
    ],
    highlights: ['Aurora chase', 'Dog sledding', 'Fjord cruise'],
    description: 'Arctic skies, cozy lodges, and crackling campfires.',
    inclusions: ['Round-trip flights', 'Lodge stay with breakfast', 'Aurora hunt tour', 'Dog sledding experience'],
    notIncluded: ['Lunch and dinner', 'Winter gear rental', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & settle', detail: 'Check-in, harbor walk.' },
      { day: 'Day 2', title: 'Aurora hunt', detail: 'Night chase with guide.' },
      { day: 'Day 3', title: 'Dogs & fjords', detail: 'Dog sled morning, fjord cruise afternoon.' },
      { day: 'Day 4-5', title: 'Sauna & depart', detail: 'Sauna time, souvenir stop, fly home.' },
    ],
  },
  {
    id: 17,
    title: 'California Loop',
    location: 'San Francisco & Yosemite, USA',
    duration: '6 Days / 5 Nights',
    price: '$1,390',
    priceValue: 1390,
    originalPrice: 1550,
    discount: '-10% today',
    badge: 'Road trip',
    reviews: 210,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=0',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=0',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Golden Gate sunset', 'Yosemite day trip', 'Napa tasting'],
    description: 'Coastal drives, towering granite cliffs, and wine country evenings.',
    inclusions: ['Round-trip flights', 'Hotels with breakfast', 'Yosemite tour', 'Napa tasting'],
    notIncluded: ['Lunch and dinner', 'Car rental add-ons', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive SF', detail: 'Fisherman’s Wharf, cable cars.' },
      { day: 'Day 2', title: 'City icons', detail: 'Golden Gate, Alamo Square, ferry building.' },
      { day: 'Day 3', title: 'Yosemite', detail: 'Full-day guided valley tour.' },
      { day: 'Day 4-6', title: 'Napa & coast', detail: 'Wine tasting, coastal detour, depart.' },
    ],
  },
  {
    id: 18,
    title: 'Island Luxe',
    location: 'Maldives',
    duration: '5 Days / 4 Nights',
    price: '$2,150',
    priceValue: 2150,
    originalPrice: 2380,
    discount: '-10% today',
    badge: 'Overwater',
    reviews: 89,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80&auto=format&fit=crop&sat=5',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Overwater villa', 'Sandbank picnic', 'Snorkel safari'],
    description: 'Turquoise lagoons, private decks, and endless horizon swims.',
    inclusions: ['Round-trip flights', 'Overwater villa with breakfast', 'Speedboat transfers', 'Snorkel excursion'],
    notIncluded: ['Lunch and dinner', 'Seaplane upgrade', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & lagoon', detail: 'Check-in, sunset swim.' },
      { day: 'Day 2', title: 'Sandbank day', detail: 'Private picnic, snorkeling.' },
      { day: 'Day 3', title: 'Reef safari', detail: 'Guided reef swim with marine life.' },
      { day: 'Day 4-5', title: 'Spa & depart', detail: 'Spa morning, paddle board, departure.' },
    ],
  },
  {
    id: 19,
    title: 'Outback Wonders',
    location: 'Sydney & Uluru, Australia',
    duration: '7 Days / 6 Nights',
    price: '$1,980',
    priceValue: 1980,
    originalPrice: 2180,
    discount: '-9% today',
    badge: 'Iconic',
    reviews: 134,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop&sat=12',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=12',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=0',
    ],
    highlights: ['Opera House tour', 'Bondi walk', 'Uluru sunset'],
    description: 'Harbor sails, red-rock sunsets, and coastal café culture.',
    inclusions: ['Round-trip flights', 'Hotels with breakfast', 'Uluru day tour', 'Domestic flights included'],
    notIncluded: ['Lunch and dinner', 'Harbor cruise optional', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Sydney', detail: 'Harbor stroll, The Rocks.' },
      { day: 'Day 2', title: 'Opera & Bondi', detail: 'Opera House tour, coastal walk.' },
      { day: 'Day 3', title: 'Fly to Uluru', detail: 'Sunset at Uluru-Kata Tjuta.' },
      { day: 'Day 4-7', title: 'Desert & return', detail: 'Field of Light, flight back, depart.' },
    ],
  },
  {
    id: 20,
    title: 'Baltic Breeze',
    location: 'Tallinn, Estonia',
    duration: '4 Days / 3 Nights',
    price: '$760',
    priceValue: 760,
    originalPrice: 840,
    discount: '-9% today',
    badge: 'Old town',
    reviews: 87,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=25',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=25',
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=10',
    ],
    highlights: ['Medieval old town', 'Sauna evening', 'Seaside Telliskivi'],
    description: 'Cobblestones, cozy cafés, and a modern creative district by the sea.',
    inclusions: ['Round-trip flights', 'Central boutique stay', 'Old town walking tour', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Sauna add-on', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & wander', detail: 'Town Hall Square, cinnamon buns.' },
      { day: 'Day 2', title: 'History walk', detail: 'Walls, towers, hidden courtyards.' },
      { day: 'Day 3', title: 'Modern Tallinn', detail: 'Telliskivi design stops, sauna evening.' },
      { day: 'Day 4', title: 'Depart', detail: 'Final coffee, flight home.' },
    ],
  },
  {
    id: 21,
    title: 'Tea Hills',
    location: 'Ella, Sri Lanka',
    duration: '5 Days / 4 Nights',
    price: '$910',
    priceValue: 910,
    originalPrice: 1010,
    discount: '-10% today',
    badge: 'Scenic rail',
    reviews: 156,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200&q=80&auto=format&fit=crop&sat=10',
    images: [
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Train through tea fields', 'Little Adam’s Peak', 'Nine Arches Bridge'],
    description: 'Emerald hills, waterfall hikes, and slow trains above the clouds.',
    inclusions: ['Round-trip flights', 'Hill-country hotel with breakfast', 'Train tickets', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Safari add-on', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & unwind', detail: 'Tea factory welcome, sunset view.' },
      { day: 'Day 2', title: 'Scenic rail', detail: 'Train ride, bridge photo stop.' },
      { day: 'Day 3', title: 'Hike day', detail: 'Little Adam’s Peak, waterfall dip.' },
      { day: 'Day 4-5', title: 'Cafés & depart', detail: 'Ella cafés, massage, flight home.' },
    ],
  },
  {
    id: 22,
    title: 'Sakura Stroll',
    location: 'Osaka & Nara, Japan',
    duration: '5 Days / 4 Nights',
    price: '$1,180',
    priceValue: 1180,
    originalPrice: 1320,
    discount: '-11% today',
    badge: 'Spring picks',
    reviews: 198,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80&auto=format&fit=crop&sat=0',
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=80&auto=format&fit=crop&sat=0',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=-5',
    ],
    highlights: ['Osaka food crawl', 'Nara deer park', 'Osaka Castle blossoms'],
    description: 'Street food nights, lantern-lit castles, and spring petals underfoot.',
    inclusions: ['Round-trip flights', 'Hotel with breakfast', 'Nara day trip', 'Transit IC card'],
    notIncluded: ['Lunch and dinner', 'USJ tickets', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & Dotonbori', detail: 'Neon food crawl night.' },
      { day: 'Day 2', title: 'Osaka Castle', detail: 'Castle grounds, riverside walk.' },
      { day: 'Day 3', title: 'Nara day', detail: 'Temples, deer park, mochi pounding.' },
      { day: 'Day 4-5', title: 'Free & depart', detail: 'Shopping arcades, café, fly home.' },
    ],
  },
  {
    id: 23,
    title: 'Samba Nights',
    location: 'Rio de Janeiro, Brazil',
    duration: '6 Days / 5 Nights',
    price: '$1,320',
    priceValue: 1320,
    originalPrice: 1460,
    discount: '-10% today',
    badge: 'Beach + city',
    reviews: 241,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=25',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=25',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Christ the Redeemer', 'Sugarloaf sunset', 'Samba night'],
    description: 'Iconic peaks, caipirinhas, and music that spills into the streets.',
    inclusions: ['Round-trip flights', 'Beach hotel with breakfast', 'Corcovado tour', 'Sugarloaf tickets'],
    notIncluded: ['Lunch and dinner', 'Favela tour optional', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival & Copacabana', detail: 'Beach walk, sunset drink.' },
      { day: 'Day 2', title: 'Christ the Redeemer', detail: 'Morning visit, Selarón steps.' },
      { day: 'Day 3', title: 'Sugarloaf', detail: 'Cable car sunset, samba night.' },
      { day: 'Day 4-6', title: 'Beaches & depart', detail: 'Ipanema time, market, flight home.' },
    ],
  },
  {
    id: 24,
    title: 'Nordic Design',
    location: 'Copenhagen, Denmark',
    duration: '4 Days / 3 Nights',
    price: '$990',
    priceValue: 990,
    originalPrice: 1090,
    discount: '-9% today',
    badge: 'Cycling city',
    reviews: 156,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80&auto=format&fit=crop&sat=15',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=15',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Nyhavn harbor', 'Bike tour', 'Design museums'],
    description: 'Harbor hues, pastries, and sleek Scandinavian design stops.',
    inclusions: ['Round-trip flights', 'Central hotel with breakfast', 'Guided bike tour', 'Canal cruise tickets'],
    notIncluded: ['Lunch and dinner', 'Museum entries not listed', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & stroll', detail: 'Nyhavn sunset, smørrebrød.' },
      { day: 'Day 2', title: 'Bike the city', detail: 'Design highlights, parks.' },
      { day: 'Day 3', title: 'Museums & food', detail: 'Designmuseum, Torvehallerne market.' },
      { day: 'Day 4', title: 'Depart', detail: 'Canal cruise, fly home.' },
    ],
  },
  {
    id: 25,
    title: 'Canyon Colors',
    location: 'Sedona, USA',
    duration: '4 Days / 3 Nights',
    price: '$780',
    priceValue: 780,
    originalPrice: 860,
    discount: '-9% today',
    badge: 'Red rocks',
    reviews: 102,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80&auto=format&fit=crop&sat=20',
    images: [
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=20',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=15',
    ],
    highlights: ['Cathedral Rock hike', 'Jeep tour', 'Stargazing'],
    description: 'Sunset-red cliffs, vortex views, and dark-sky nights.',
    inclusions: ['Round-trip flights', 'Resort stay with breakfast', 'Jeep tour', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Spa treatments', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & unwind', detail: 'Red rock views, spa time.' },
      { day: 'Day 2', title: 'Jeep adventure', detail: 'Off-road canyons and vistas.' },
      { day: 'Day 3', title: 'Hike & stars', detail: 'Cathedral Rock, stargazing night.' },
      { day: 'Day 4', title: 'Depart', detail: 'Breakfast, flight home.' },
    ],
  },
  {
    id: 26,
    title: 'Alpine Lakes',
    location: 'Banff, Canada',
    duration: '5 Days / 4 Nights',
    price: '$1,180',
    priceValue: 1180,
    originalPrice: 1290,
    discount: '-9% today',
    badge: 'Nature',
    reviews: 165,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80&auto=format&fit=crop&sat=10',
    images: [
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=10',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=5',
    ],
    highlights: ['Lake Louise', 'Moraine Lake', 'Gondola ride'],
    description: 'Glacial blues, mountain air, and wildlife-filled valleys.',
    inclusions: ['Round-trip flights', 'Mountain lodge with breakfast', 'Lake shuttle', 'Park pass'],
    notIncluded: ['Lunch and dinner', 'Canoe rentals', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Banff', detail: 'Check-in, Bow River walk.' },
      { day: 'Day 2', title: 'Lake Louise', detail: 'Shuttle, lakeside hike.' },
      { day: 'Day 3', title: 'Moraine morning', detail: 'Sunrise view, gondola ride.' },
      { day: 'Day 4-5', title: 'Trails & depart', detail: 'Easy trail day, café, flight home.' },
    ],
  },
  {
    id: 27,
    title: 'Sahara Skies',
    location: 'Fes & Merzouga, Morocco',
    duration: '6 Days / 5 Nights',
    price: '$1,140',
    priceValue: 1140,
    originalPrice: 1260,
    discount: '-9% today',
    badge: 'Desert camp',
    reviews: 118,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80&auto=format&fit=crop&sat=25',
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&q=80&auto=format&fit=crop&sat=25',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop&sat=10',
    ],
    highlights: ['Fes medina', 'Desert camp', 'Camel trek'],
    description: 'Ancient alleys to endless dunes with starry-night camps.',
    inclusions: ['Round-trip flights', 'Riads with breakfast', 'Camel trek & camp', 'Private transfers'],
    notIncluded: ['Lunch and dinner', 'Sandboarding add-on', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Fes', detail: 'Medina intro, rooftop dinner.' },
      { day: 'Day 2', title: 'Fes deep dive', detail: 'Tanneries, madrasas, artisans.' },
      { day: 'Day 3', title: 'To Sahara', detail: 'Drive via Atlas, camel trek to camp.' },
      { day: 'Day 4-6', title: 'Sunrise & return', detail: 'Dunes sunrise, back to Fes, depart.' },
    ],
  },
  {
    id: 28,
    title: 'Highland Trails',
    location: 'Edinburgh & Highlands, UK',
    duration: '5 Days / 4 Nights',
    price: '$1,040',
    priceValue: 1040,
    originalPrice: 1140,
    discount: '-9% today',
    badge: 'Castles',
    reviews: 174,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80&auto=format&fit=crop&sat=5',
    images: [
      'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1400&q=80&auto=format&fit=crop&sat=5',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&q=80&auto=format&fit=crop',
    ],
    highlights: ['Edinburgh Castle', 'Loch Ness', 'Highlands day trip'],
    description: 'Storybook closes, castle spires, and misty glens.',
    inclusions: ['Round-trip flights', 'Hotel with breakfast', 'Highlands day tour', 'Airport transfers'],
    notIncluded: ['Lunch and dinner', 'Whisky tasting optional', 'Travel insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & Royal Mile', detail: 'Old Town walk, pub dinner.' },
      { day: 'Day 2', title: 'Castle & museums', detail: 'Castle visit, National Museum.' },
      { day: 'Day 3', title: 'Highlands loop', detail: 'Loch Ness, Glencoe vistas.' },
      { day: 'Day 4-5', title: 'Dean Village & depart', detail: 'Water of Leith stroll, fly home.' },
    ],
  },
]

export const getPackageById = (id) => packagesData.find((item) => item.id === Number(id))
